name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          check-latest: false
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Install Expo CLI
        run: yarn global add expo-cli

      - name: Install modules
        run: yarn install --network-concurrency 1

      - name: Prepare packages
        run: yarn pre

      - name: Check linting
        run: yarn lint

      - name: Build typescript
        run: yarn tsc

      - name: Build
        run: yarn build

      - name: Remove theme built lib
        run: rm -rf packages/theme/lib

      - name: Test
        run: |
          export NODE_OPTIONS="--max-old-space-size=8192"
          npx jest --coverage --forceExit --silent -u

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
          path_to_write_report: ./coverage/codecov_report.gz
