name: Deploy docs on merge
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'docs/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 15.x

      - name: Install packages and build storybook
        run: |
          pushd ./docs
          yarn
          yarn preinstall
          yarn build
          popd

      - name: Deploy to firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: './docs'
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: dooboolab-2f044
          target: dooboo-ui
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
