name: Deploy docs on merge
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Expo CLI
        run: yarn global add expo-cli

      - name: Install packages and build storybook
        run: |
          pushd ./docs
          yarn install --network-concurrency 1
          yarn build
          popd

      - name: Deploy to firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: './docs'
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DOOBOOLAB_2F044 }}'
          channelId: live
          projectId: dooboolab-2f044
          target: dooboo-ui
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
