name: gh-pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'stories/**/*'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Setup expo cli
        uses: expo/expo-github-action@v8
        with:
          expo-version: 4.x

      - name: Install dependencies
        run: yarn install --network-concurrency 1

      - name: Lerna setup for packages
        run: yarn pre

      - name: Install packages and build storybook
        run: |
          yarn export

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_branch: gh-pages
          publish_dir: ./dist
          # Required in Expo
          enable_jekyll: false
          SCRIPT_MODE: true
