name: gh-pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'stories/**/*'

jobs:
  build_and_deploy:
    if: github.repository == 'dooboolab/dooboo-ui'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 18.x

      - name: Setup expo cli
        uses: expo/expo-github-action@v8
        with:
          expo-version: 4.x

      - name: Install dependencies
        run: yarn install --ignore-engines --network-concurrency 1

      - name: Lerna setup for packages
        run: yarn pre

      - name: Install packages and build storybook
        run: |
          yarn build:storybook

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_branch: gh-pages
          publish_dir: ./web-build
          SCRIPT_MODE: true
